#!/usr/bin/env bash
set -euo pipefail

# Simple retrain trigger based on drift score.
# Requires: monitoring/training_stats.json and runtime/predictions.db (generated by running the API).

DB_PATH=${DB_PATH:-runtime/predictions.db}
THRESHOLD=${THRESHOLD:-0.2}

if [ ! -f "monitoring/training_stats.json" ]; then
  echo "Missing monitoring/training_stats.json. Run training first." >&2
  exit 1
fi

if [ ! -f "$DB_PATH" ]; then
  echo "Missing $DB_PATH. Run the API and generate some predictions first." >&2
  exit 1
fi

python - <<PY
import os
from app.db import fetch_recent_inputs
from monitoring.drift import load_training_stats, drift_report

training = load_training_stats("monitoring/training_stats.json")
live = fetch_recent_inputs(limit=500, db_path=os.environ.get("DB_PATH","$DB_PATH"))
rep = drift_report(training, live)
print("Drift report:", rep)

threshold = float(os.environ.get("THRESHOLD", "$THRESHOLD"))
if rep["drift_score"] >= threshold:
    print(f"\nDrift score >= {threshold}. Triggering retraining...")
    raise SystemExit(10)
else:
    print(f"\nDrift score < {threshold}. No retraining needed.")
PY

CODE=$?
if [ $CODE -eq 10 ]; then
  bash scripts/train.sh
  bash scripts/promote.sh models/bert_sentiment v2
  echo "Retraining done. Rebuild and restart container to use the new model."
  exit 0
fi
